cities:
  - name: "Warsaw"
    lat: 52.2319581
    lon: 21.0067249
  - name: "Berlin"
    lat: 52.5170365
    lon: 13.3888599
  - name: "Paris"
    lat: 48.8588897
    lon: 2.3200410217200766
  - name: "Rome"
    lat: 41.8933203
    lon: 12.4829321
  - name: "Madrid"
    lat: 40.4167047
    lon: -3.7035825